language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed shambi21/udagram-api-feed:v1
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user shambi21/udagram-api-user:v1
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend shambi21/udagram-frontend:v1
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy shambi21/reverseproxy:v1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push shambi21/udagram-api-feed:v1
  - docker push shambi21/udagram-api-user:v1
  - docker push shambi21/udagram-frontend:v1
  - docker push shambi21/reverseproxy:v1
  

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "Done"